name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tags
        id: docker_tags
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "tags=ghcr.io/${{ github.repository_owner }}/ci-lark-notification:latest" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tags=ghcr.io/${{ github.repository_owner }}/ci-lark-notification:latest,ghcr.io/${{ github.repository_owner }}/ci-lark-notification:${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull image from GHCR
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/ci-lark-notification:${{ github.ref_name }}

      - name: Tag and push to Docker Hub
        run: |
          # Tag the GHCR image for Docker Hub
          docker tag ghcr.io/${{ github.repository_owner }}/ci-lark-notification:${{ github.ref_name }} ${{ secrets.DOCKERHUB_USERNAME }}/ci-lark-notification:${{ github.ref_name }}
          docker tag ghcr.io/${{ github.repository_owner }}/ci-lark-notification:${{ github.ref_name }} ${{ secrets.DOCKERHUB_USERNAME }}/ci-lark-notification:latest

          # Push to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-lark-notification:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-lark-notification:latest
